### ISSUE TITLE
FILTER_SANITIZE_STRING warning

### ISSUE THREAD

**Issue by ned-bs** [woocommerce/facebook-for-woocommerce#2588]
Hi there,

This plugin uses the deprecated ( as of PHP 8.1.0 ) \facebook-for-woocommerce\includes\Framework\Helper.php line 141 and also lne 143.

According to PHP.net it should be replaced with htmlspecialchars() – https://www.php.net/manual/en/function.htmlspecialchars.php

Looking forward to an update on this issue.

Thank you!

`	public static function str_to_ascii( $string ) {
		// strip ASCII chars 32 and under
		$string = filter_var( $string, FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW );
		// strip ASCII chars 127 and higher
		return filter_var( $string, FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_HIGH );
	}`

**Comment by layoutd** [comment]
Thanks for the report @bsahins, we'll update here when the fix is released.

**Comment by WouterBossen** [comment]
Hey guys, any update on this? It's been a year and we're still getting the deprecated message.

**Comment by theavijitsarkar** [comment]
Kindly fix this, this is causing a mayhem in my debug log file

**Comment by layoutd** [comment]
👋🏻  @ned-bs @WouterBossen @theavijitsarkar 
This issue has been addressed and the fix should be included in next week's release.
